### ISSUE TITLE
Notas Destinadas

### ISSUE THREAD

**Issue by tiagocardosos** [leotada/PyNFe#14]
Olá, estou testando a consulta de notas destinadas para o DF. Porém o meu retorno é apenas de notas do dia isso com o NSU=0. Testei com alguns CNPJs e efetuei o mesmo teste em outro projeto que PHP e realmente o meu retorno foi NFes apenas do dia. 

Teria alguma ideia do problema?

**Comment by juniortada** [comment]
Tiago, NSU=0 retorna apenas as ultimas notas recepcionadas seguido de um novo NSU. Para receber mais notas vc deve consultar novamente com o novo NSU passado na ultima consulta e assim sucessivamente.

"A aplicação cliente do WS deve informar o último número sequencial único - ultNSU que possui.
Caso o ultNSU seja informado com 0 (zero), o WS fará a consulta a partir da primeira nota fiscal
recepcionada há menos de 15 dias ou outro prazo maior que a UF entender conveniente;
IMPORTANTE: O campo ultNSU representa a numeração única da NF-e dentro do ambiente que
está sendo consultado. Se estiver sendo consultado o AN, este será o valor do NSU_RFB. Se
tiver sendo consulta uma determinada SEFAZ, este será o valor do NSU_SEFAZ_XX."

Mais informações na NT 2012_002.

http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=bUBJ/PmtKQo=

**Comment by tiagocardosos** [comment]
@juniortada, o método utilizado atualmente é o NfeConsultaDest. Na verdade eu estava esperando o resultado do NFeDistribuicaoDFe. Este método me retorna XML's já manifestados, eventos e o cabeçalho das notas emitidas.

Inclusive, me parece que tem nota técnica informando que o NfeConsultaDest será desativado.

Caso queira implementar no projeto:
Url: https://hom.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx
XML:
```<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soap:Header/><soap:Body><nfeDistDFeInteresse xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe"><nfeDadosMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe"><distDFeInt versao="1.01" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><cUFAutor>53</cUFAutor><CNPJ>72614092000100</CNPJ><distNSU><ultNSU>000000000000000</ultNSU></distNSU></distDFeInt></nfeDadosMsg></nfeDistDFeInteresse></soap:Body></soap:Envelope>```

**Comment by juniortada** [comment]
Sim, será desativado. Dia 01/06/2017 inicia o ambiente de homologação da versão 4.00, vamos fazer grandes modificações PyNFe e não iremos mais desenvolver a versão 3.10 que tem prazo para desativação para 02/04/2018 (era 06/11/2017, mas foi prorrogado).

Sobre a NFeDistribuicaoDFe, nem todas as SEFAZ aderiram aos sistema completo, acho que o mais completo é da SEFAZ RS. E nem todas as SEFAZ atualizam o AN regularmente.
Esse WS foi apresentado na NT 2014_002, já está na quarta revisão. Eu até cheguei a fazer alguns testes mas fiquei aguardando uma definição maior por parte das SEFAZ. Está mais ou menos como a NFC-e, cada SEFAZ implementou um método próprio com suas próprias variações. 

NT 2012_002
https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=VcEhGZODuo4=
