### ISSUE TITLE
Assinatura XML

### ISSUE THREAD

**Issue by makomm** [leotada/PyNFe#16]
Olá,
Estou tendo que emitir NFe na minha empresa e achei o projeto de vocês muito interessante. Mas estou tendo um problema na assinatura do XML, por algum motivo o xml final sai com 4 campos X509, o motivo é conhecido? Estou usando Windows.
Obrigado desde já!

**Comment by juniortada** [comment]
Vc precisa exportar o seu certificado desmarcando uma opção. Siga esse tutorial e no passo 6 DESMARQUE a opção: include all certificates in the certificate path if possible
https://www.digicert.com/code-signing/exporting-code-signing-certificate.htm

**Comment by makomm** [comment]
Obrigado pela ajuda! Não sei se foi muita falta de informação minha, mas fica aqui a sugestão: não seria útil acrescentar na wiki essa informação? Obrigado novamente!

**Comment by juniortada** [comment]
Criado nova classe de assinatura que permite assinatura com certificado duplicado.
https://github.com/leotada/PyNFe/commit/264ea14bede3e258b5be9ee118596302bea190c3
