### ISSUE TITLE
Arrumar pip install (TO-DO)

### ISSUE THREAD

**Issue by leonardoRC** [leotada/PyNFe#17]
Fazer a instalação automatica por pip install permitendo selecionar a versão,
utilizando com as opções dos lest stables e o beta atual(last commit).
Ajusta o arquivo setup.py

**Comment by leotada** [comment]
Pretendemos criar um novo repositório não sendo um fork, talvez com outro nome para diferenciar, e aí sim colocar no PyPi.

**Comment by leonardoRC** [comment]
Perfeito.
