### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by leonardoRC** [leotada/PyNFe#2]
Utilizaremos para documentar a wiki do próprio github?
Ou utilizaremos o docs de readthedocs?
Utilizando a do read ele é mais complicado...

**Comment by leotada** [comment]
Então como não sabemos usar a do readthedocs direito, colocamos uns exemplos na wiki mesmo, mas se depois alguem quiser contribuir criando/atualizando a versão do readthedocs é bem vindo.

**Comment by leonardoRC** [comment]
ok vamos seguir nesta linha...
