### ISSUE TITLE
Download xml 

### ISSUE THREAD

**Issue by Danhcarvalho** [leotada/PyNFe#23]
Pessoal,

Estou com este problema quando tento conectar ao webservice sefaz https://hom.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx para fazer o download do xml. Este link é o novo utilizado pelo Sefaz, pois o webservice de Download de NFe foi terminado.

Isso que recebo de mensagem debugando no pycharm
ComunicacaoSefaz.download() = {Response} <Response [500]>
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><soap:Code><soap:Value>soap:Sender</soap:Value></soap:Code><soap:Reason><soap:Text xml:lang="en">Unable to handle request without a valid action parameter. Please supply a valid soap action.</soap:Text></soap:Reason><soap:Detail /></soap:Fault></soap:Body></soap:Envelope>'
_content_consumed = {bool} True
_next = {NoneType} None
apparent_encoding = {str} 'ascii'
Estou utilizando um certificado valido.

Obrigado pela ajuda!!!

**Comment by juniortada** [comment]
Qual versão vc está utilizando, o branch master ou a versão 3.10?

**Comment by Danhcarvalho** [comment]
Junior 
3.10

**Comment by juniortada** [comment]
Essa versão teve o desenvolvimento encerrado devido a nova versão 4.00, não sei como vai ficar a questão do download ainda, pq não tem url para versão 4.00 e o protocolo de comunicação agora é diferente e incompatível (soap e tls).

**Comment by Danhcarvalho** [comment]
Junior,

Entendi, mas vi que o pessoal de java estava utilizando este webservice https://hom.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx na versão 1.0 com a alteração do xml para o abaixo e conseguiram. 

Eu mudei o xml, mas continuo com o mesmo erro 

<?xml version="1.0" encoding="UTF-8"?>  
<distDFeInt xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.01">  
  <tpAmb>X AMBIENTE</tpAmb>  
  <cUFAutor>xxx UF</cUFAutor>  
  <CNPJ>XXXXXXXXXXX CNPJ</CNPJ>  
  <consChNFe>  
    <chNFe>XXXXXXXXXXXXX CHAVE</chNFe>  
  </consChNFe>  
</distDFeInt>  

Obrigado pela resposta!

**Comment by Danhcarvalho** [comment]
Segue xml 

<?xml version="1.0" encoding="UTF-8"?>  
<distDFeInt xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.01">  
  <tpAmb>X AMBIENTE</tpAmb>  
  <cUFAutor>xxx UF</cUFAutor>  
  <CNPJ>XXXXXXXXXXX CNPJ</CNPJ>  
  <consChNFe>  
    <chNFe>XXXXXXXXXXXXX CHAVE</chNFe>  
  </consChNFe>  
</distDFeInt>

**Comment by juniortada** [comment]
Na versão 3.10 eu tenho quase certeza que não irá funcionar. 
Na 4.00 se a SEFAZ não lançar uma versão compatível de webservice, eu terei que criar uma forma de "emular" o padrão de comunicação antigo na versão nova.
Mas isto ainda não está pronto e deverá demorar algum tempo até que seja implementado. 
A prioridade no momento é a emissão, consulta, cancelamento, etc, para entrada em produção da versão 4.00.

**Comment by Danhcarvalho** [comment]
Junior,

Eu consegui adaptar o código para fazer o "dowload do xml" na verdade retornou o print. Como faço para baixar o arquivo porque no código só tem o print. E seria interessante você postar o código que eu adaptei para quem precisar.

Grato

**Comment by juniortada** [comment]
Faz um fork do projeto, faça as modificações e depois solicite um pull request que eu adiciono a sua contribuição no repositório do branch 3.10, faça o commit nesta versão do branch.
