### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Danhcarvalho** [leotada/PyNFe#24]
Pessoal,

Estou tendo o seguinte erro [WinError 2] The system cannot find the file specified utlizando o manifesto ciência da emissão. Esta exceção ocorre na linha do subprocess.check_call. Estou utilizando a versão 3.1

subprocess.check_call(['xmlsec1', '--sign', '--pkcs12', self.certificado, '--pwd', self.senha, '--crypto', 'openssl', '--output', 'funfa.xml', '--id-attr:Id', tag, 'testes.xml'])
            xml = etree.parse('funfa.xml').getroot()

            if retorna_string:
                return etree.tostring(xml, encoding="unicode", pretty_print=False)
            else:
                return xml
        except Exception as e:[WinError 2] The system cannot find the file specified
Grato

**Comment by leotada** [comment]
Você está utilizando o método de assinatura que usa o XMLSec que não está instalado.
Prefira utilizar o novo método com SignXML, troque AssinaturaA1 por AssinaturaA1SignXML no seu código, e instale o módulo signxml pelo pip.

**Comment by Danhcarvalho** [comment]
Leo,
Alterei como você falou e realmente não tive mais este erro. No xml abaixo eu tive esse erro 2254 - Falha na validação de esquema Xml, mas não sei dizer se o evento funcionou ou não. Fiz o teste no ambiente de homologação

Agradeço explicação.

<?xml version="1.0" encoding="utf-8"?>
 <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	 <soap:Body>
		 <nfeRecepcaoEventoResult xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento">
			 <retEnvEvento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe">
				<idLote>000000000000000</idLote>
				 <tpAmb>2</tpAmb>
				 <verAplic>AN_1.0.0</verAplic>
				 <cOrgao>91</cOrgao>
				 <cStat>999</cStat>
				 <xMotivo>2254 - Falha na validação de esquema Xml</xMotivo>
			 </retEnvEvento>
		 </nfeRecepcaoEventoResult>
	 </soap:Body>
 </soap:Envelope>
