### ISSUE TITLE
Posso fazer consultas de notas sem chave?

### ISSUE THREAD

**Issue by daherk2** [leotada/PyNFe#28]

**Comment by daherk2** [comment]
Gostaria de consultar notas sem necessitar de ComunicacaoSefaz(uf, certificado, senha, homologacao)

**Comment by juniortada** [comment]
"Sem chave" vc quer dizer sem certificado digital? Ou sem a chave de identificação da NF-e?

**Comment by juniortada** [comment]
Bom como não pode em nenhum dos casos, vou explicar ambos:
Sem o certificado não é possível, a SEFAZ só permite que o emitente, o cliente ou a transportadora tenha acesso a NF-e, por questões de segurança no momento da conexão com o webservice é necessário o certificado digital para garantir que quem está utilizando o serviço seja algum desses envolvidos (algumas SEFAZ permitem que o contador responsável pelo emitente consulte as notas).
Sem a chave (que é um numero calculado com várias informações da NF-e + random hash) também não é possível para evitar que sistemas fiquem consultado notas em sequência sobrecarregando assim os servidores da SEFAZ.
Espero que tenha solucionado a sua dúvida!
