### ISSUE TITLE
Certificado A3

### ISSUE THREAD

**Issue by lucasm310** [leotada/PyNFe#6]
Boa tarde tem alguma ideia de como trabalhar com o certificado A3?

**Comment by juniortada** [comment]
Lucas o problema do certificado A3 é que ele não pode ser copiado/transferido, então no momento de assinar e enviar a NF-e seria necessário um "programa" instalado em cada terminal de uso. Como os sistemas que implementei ou foram web ou API, certificado A3 foi descartado do escopo pq seria inseguro deixar o certificado conectado no servidor.
Da uma olhada no Pole ou no Pyspeed mas acho que nenhum trabalha com certificado A3.

**Comment by lucasm310** [comment]
Entendi.

Att;
Lucas Augusto de Morais


Em 8 de junho de 2016 14:21, Junior Tada <notifications@github.com>
escreveu:

**Comment by diegobill** [comment]
@juniortada, pq é inseguro utilizar o certificado A3 no backend de uma aplicação para emitir NF-e?

**Comment by juniortada** [comment]
@diegobill é que o propósito do certificado A3 é ser conectado ao pc apenas no momento da ação. E na emissão da NF-e é necessário o certificado em dois momentos: para assinar o xml que será enviado e na comunicação com a SEFAZ. 
Não é que o A3 seja inseguro para emitir NF-e, é inseguro vc deixar ele conectado o tempo todo em um servidor por exemplo.

**Comment by juniortada** [comment]
@lucasm310  existem outros dois emissores de NF-e escritos em python, eu não sei se eles emitem para A3. Entra em contato com os desenvolvedores.
https://github.com/JuniorPolegato/pole
https://github.com/aricaldeira/PySPED
