### ISSUE TITLE
DANFE

### ISSUE THREAD

**Issue by tporto** [leotada/PyNFe#8]
Como funciona a impressão do DANFE?

**Comment by juniortada** [comment]
A impressão do Danfe não está incluído no pacote PyNFe, vc pode utilizar qualquer programa para gerar o Danfe a partir do xml na NF-e.
Aqui em um exemplo de como gerar o Danfe utilizando Java e jasper.
https://github.com/juniortada/Java-Danfe

**Comment by tporto** [comment]
Bacana! Trabalho com NF-e há 6 anos usando delphi com o pacote acbr(http://www.projetoacbr.com.br/forum/), pretendo migrar para web, mas ainda estou estudando python/django. Espero contribuir com o projeto e até buscarmos uma solução para impressão do DANFE no próprio projeto.
Abraço e parabéns pela iniciativa.

**Comment by juniortada** [comment]
Obrigado Thiago e seja bem vindo para participar do projeto. O python na minha opinião ainda não tem nenhuma lib para geração de relatórios com a mesma agilidade de desenvolvimento como outras linguagens. Talvez as ferramentas mais produtivas sejam as que transformam layouts html em pdf. Como todos os relatórios do meu ERP estavam em jasper acabei por manter assim a impressão do Danfe nos meus produtos. Mas minha ideia é sim adicionar uma impressão nativa em python.
