### ISSUE TITLE
Unittests não funcionando

### ISSUE THREAD

**Issue by agutoli** [leotada/PyNFe#9]
Amigos, tudo bem? Baixei o projeto e tentei rodar os testes, isso é esperado ou pode ser um problema do meu ambiente?
- gerei as chaves com `separarpfx.sh`
- rodei o servidor `run_fake_soap_server.py`
- e executei o `run_tests.py`

**Comment by leotada** [comment]
Olá, isso é esperado, os testes não estão funcionando e são do antigo PyNFe (tem 7 anos). Devem ser reescritos para funcionar. Só o separarpfx.sh que separa a chave do certificado que funciona.
Se quiser contribuir em algo, é muito bem-vindo.
